python3 /data/wsq96/CLC_data/CLC/train_CLC.py \
    -d /img_video/img/Flicker2W.hdf5 \
    --ref_path /img_video/img/Flicker2K.hdf5 \
    --feature_cache_path /h3cstore_ns/ydchen/code/CompressAI/data_cluster_feature/flicker_features.pkl \
    --save_path /data/wsq96/CLC_data/CompressAI/LIC_TCM/trained_model_1023_cyd_test \
    --lambda 0.01 \
    --epochs 50 \
    --batch-size 1 \
    --learning-rate 1e-4 \
    --n_refs 3 \
    --n_clusters 1000 \
    --type mse \
    --patch-size 256 256 \
    --cuda \
    --use-mixed-precision \
    --num-workers 0
